load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library", "rust_test")

rust_library(
    name = "files",
    srcs = glob(["*.rs"]),
)

rust_test(
    name = "files_test",
    srcs = glob(["*.rs"]),
)
